Numpy - Numerical Python

Advantages of Numpy Array:
1. Allows several Mathematical Operations
2. Faster operations


In [1]:
import numpy as np

In [2]:
# list
list1=[1,2,3,4,56,5]
print(list1)
type(list1)

[1, 2, 3, 4, 56, 5]


list

In [3]:
np_array=np.array([(1,2,3,4)])
print(np_array)
type(np_array)

[[1 2 3 4]]


numpy.ndarray

Note here that the numpy array is not comma-separated

In [4]:
# creating a one-dimensional array
a=np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [5]:
# creating a two-dimensional array
b=np.array([(1,2,3,4,5),(1,2,3,4,5)])
print(b)
print(b.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [7]:
# Making a array in other dataType beacause the default is int
c=np.array([(1,2,3,4,5),(1,2,3,4,5)],dtype=float)
print(c)


[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


Initial PlaceHolder

In [10]:
# Initializing with zero
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# Initializing with ones
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# array of a particular value
y=np.full((4,3),7)
print(y)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [14]:
# creating a identity matrix
z=np.eye(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# creating a numpy array with random values
x=np.random.random((5,3))
print(x)

[[0.62962081 0.97425652 0.93941999]
 [0.27388204 0.89223251 0.81987327]
 [0.90059022 0.71829111 0.55094102]
 [0.1021386  0.59509069 0.74826278]
 [0.51745692 0.64284521 0.66822989]]


In [18]:
# creating a numpy array with random values of int
x=np.random.randint(20,50,(5,3))
print(x)
# From 20 to 50 of 5 Row and 3 cols

[[30 27 37]
 [29 47 44]
 [45 49 36]
 [35 22 25]
 [26 30 28]]


In [20]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [26]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [27]:
# convert a list into array
list2=[1,2,4,6,34,54]
array=np.asarray(list2)
print(array)
type(array)

[ 1  2  4  6 34 54]


numpy.ndarray

*   Analysing a numpy array

In [28]:
x=np.random.randint(10,100,(5,6))
print(x)

[[26 88 57 38 83 42]
 [76 73 72 16 50 56]
 [74 89 32 50 11 37]
 [87 93 93 93 95 41]
 [44 10 66 76 50 72]]


In [29]:
#Dimension of numpy array
print(x.shape)

(5, 6)


In [30]:
# Number of Dimension
print(x.ndim)

2


In [31]:
# Number of element in the array
print(x.size)

30


In [32]:
# Checking the dataType in the array
print(x.dtype)

int64


*  Mathematical Operaiton in Numpy array

In [35]:

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

c=a+b

print(a)
print(b)
print(c)

[[9 0 9]
 [2 6 8]
 [4 6 1]]
[[19 10 19]
 [17 15 14]
 [12 14 19]]
[[28 10 28]
 [19 21 22]
 [16 20 20]]


In [36]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[28 10 28]
 [19 21 22]
 [16 20 20]]
[[-10 -10 -10]
 [-15  -9  -6]
 [ -8  -8 -18]]
[[171   0 171]
 [ 34  90 112]
 [ 48  84  19]]
[[0.47368421 0.         0.47368421]
 [0.11764706 0.4        0.57142857]
 [0.33333333 0.42857143 0.05263158]]


In [40]:
# We can even do it with function
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.subtract(a,b))

[[28 10 28]
 [19 21 22]
 [16 20 20]]
[[171   0 171]
 [ 34  90 112]
 [ 48  84  19]]
[[0.47368421 0.         0.47368421]
 [0.11764706 0.4        0.57142857]
 [0.33333333 0.42857143 0.05263158]]
[[-10 -10 -10]
 [-15  -9  -6]
 [ -8  -8 -18]]


*   Array Manipulation

In [42]:
g=np.random.randint(10,50,(5,6))
print(g)

[[42 45 13 35 24 32]
 [29 18 41 21 15 42]
 [31 40 13 18 22 17]
 [40 31 42 33 14 39]
 [42 38 32 42 38 41]]


In [44]:
# shape
print(g.shape)

(5, 6)


In [45]:
# Transpose of the matrix
trans=np.transpose(g)
print(trans)

[[42 29 31 40 42]
 [45 18 40 31 38]
 [13 41 13 42 32]
 [35 21 18 33 42]
 [24 15 22 14 38]
 [32 42 17 39 41]]


In [46]:
# Another way of transpose
trans2=g.T
print(trans2)

[[42 29 31 40 42]
 [45 18 40 31 38]
 [13 41 13 42 32]
 [35 21 18 33 42]
 [24 15 22 14 38]
 [32 42 17 39 41]]


Resaping the array

In [47]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 8 5]
 [4 0 1]]
(2, 3)


In [50]:
b=a.reshape(3,2)
print(b)

[[6 8]
 [5 4]
 [0 1]]


Why is it important to use a numpy array when we have a list and a tuple?
1. Because a numpy array is faster
2. Speed and Performance: NumPy arrays are much faster for mathematical operations because they use vectorization, which eliminates the need for explicit loops. Their core is written in C, making operations execute much quicker.

3. Memory Efficiency: Arrays are more memory-efficient than lists because all elements are of the same data type and are stored in a contiguous block of memory. This saves a lot of space, especially for large datasets.

4. Functionality: NumPy provides a vast library of functions for linear algebra, broadcasting, and other mathematical operations that are not available for standard Python lists or tuples. This makes it a foundational library for data science and machine learning.

Some Disadvantages of the Numpy array

1. Homogeneity (Single Data Type): A NumPy array can only store elements of the same data type. This is its core strength for performance and memory efficiency, but it's also a limitation. If you need to store a mix of integers, strings, and other objects, a standard Python list is the better choice.

2. Difficulty in Resizing: Unlike Python lists which can be easily resized with methods like append() or pop(), NumPy arrays have a fixed size upon creation. If you need to change the size of an array, you have to create a new one and copy the old array's data into it. This can be computationally expensive and inefficient for tasks that require frequent modifications to the array's size.